galaxy_info:
  role_name: my_module_file_create
  namespace: qshar1408
  author: AntonGribanov
  company: GribanovAnton
  description: Role to use my first module

  license: MIT

  min_ansible_version: "2.14"

  platforms:
    - name: Ubuntu
      versions:
        - 22.04
        - 24.04

  galaxy_tags:
    - module
    - file

dependencies: []